# Generated by Django 2.2.12 on 2020-05-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDNI', models.CharField(max_length=20, verbose_name='Identificacion')),
                ('NombUser', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('apelUser', models.CharField(max_length=200, null=True, verbose_name='Apellido')),
                ('profeUser', models.CharField(max_length=100, null=True, verbose_name='Profecion')),
                ('fotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='Foto de perfil')),
                ('teleUser', models.CharField(max_length=20, verbose_name='Numero de telefono')),
                ('geneUser', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Genero')),
                ('adddata', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Datos del usuario',
                'verbose_name_plural': 'Infomacion',
            },
        ),
        migrations.CreateModel(
            name='HabilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabi', models.CharField(max_length=100)),
                ('Deschabil', models.TextField(max_length=2000, verbose_name='descrpcion de la habiliadad')),
                ('Prof', models.CharField(max_length=100, verbose_name='Profesion')),
            ],
            options={
                'verbose_name': 'habilidades de usuario',
                'verbose_name_plural': 'Infomacion',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfile de usuario',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psrHabil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('udtHabil', models.DateTimeField(auto_now=True)),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='identificador de rol')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Nivel de habilidades ',
                'verbose_name_plural': 'porcentajes',
            },
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addUser', models.DateTimeField(auto_now_add=True)),
                ('udtuser', models.DateTimeField(auto_now=True)),
                ('estaRol', models.CharField(max_length=10)),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='identificador de rol')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'roles  del usuario',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
