# Generated by Django 2.2.12 on 2020-05-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200513_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habiluser',
            options={'verbose_name': 'habilidades de usuario', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
