# Generated by Django 2.2.12 on 2020-05-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0002_auto_20200513_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=200, null=True, verbose_name='leguaje de se va utilizar')),
                ('motrDB', models.CharField(max_length=200, null=True, verbose_name='nonmbre de la base de datos')),
                ('arquitectura', models.CharField(max_length=200, null=True, verbose_name='arquitectura de software')),
            ],
            options={
                'verbose_name': 'categoria del proyecto',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDoc', models.CharField(max_length=200, null=True, verbose_name='tipo de documento')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProy', models.CharField(max_length=200, null=True, verbose_name='nombre del proyecto')),
                ('descProy', models.CharField(max_length=200, null=True, verbose_name='descripcion del proyecto')),
                ('imgProy', models.ImageField(default='proyecto.png', upload_to=None, verbose_name='Foto del Proyecto')),
                ('fechaIni', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de inicio')),
                ('fechaFin', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha fin')),
                ('urlRepo', models.TextField(max_length=200, verbose_name='link del proyecto')),
                ('estaProy', models.CharField(max_length=45, verbose_name='esta del pryecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='identificador de CategProye')),
            ],
            options={
                'verbose_name': 'tipo de proyectos',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombDocu', models.CharField(max_length=200, verbose_name='nombre del documento')),
                ('pathDocu', models.FileField(max_length=45, upload_to='', verbose_name='ruta del documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='identificador de la tabla proyectos')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='identificador de tipo de documento')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='identificador de la tabla Usuarios')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'Documento',
            },
        ),
    ]
