# Generated by Django 2.2.12 on 2020-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'tipo de proyectos', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tipodocu',
            options={'verbose_name': 'tipo de documento', 'verbose_name_plural': 'Tipo de Documento'},
        ),
        migrations.RemoveField(
            model_name='categproye',
            name='motrDB',
        ),
        migrations.AddField(
            model_name='categproye',
            name='motorDB',
            field=models.CharField(max_length=200, null=True, verbose_name='nombre de la base de datos'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='pathDocu',
            field=models.FileField(max_length=45, upload_to=None, verbose_name='ruta del documento'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechaFin',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechaIni',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha de inicio'),
        ),
    ]
