# Generated by Django 2.2.12 on 2020-05-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200513_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categproye',
            name='arquitectura',
            field=models.CharField(max_length=200, null=True, verbose_name='tipo de arquitectura de software'),
        ),
        migrations.AlterField(
            model_name='categproye',
            name='lenguaje',
            field=models.CharField(max_length=200, null=True, verbose_name='leguaje de progamacion'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estaProy',
            field=models.CharField(max_length=45, verbose_name='Estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idCategProye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='identificador de Categoria'),
        ),
    ]
