# Generated by Django 2.2.12 on 2020-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20200514_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imgProy',
            field=models.ImageField(default='proyecto.png', upload_to='img/perfiles', verbose_name='Foto del Proyecto'),
        ),
    ]
